logger:
  #Level 0 紧急的 1警报 2重要的 3错误 4警告 5提示 6信息 7调试
  consoleShow: true
  consoleLevel:  7
  fileWrite:  true
  fileLevel:  7
  multiFileWrite: false
  multiFileLevel: 7

rpcServer:
  model: 1
  serverName: "authorize"
  etcd: ["127.0.0.1:12379"]
  basePath: "go-admin"
  addr: ""
  port: 7655
  pprof: 7654

db:
  dbType: "mysql"
  maxOpenConn: 20
  maxIdleConn: 4
  maxIdleTime: 100
  maxLifeTime: 3600
  level: 4
  slowThreshold: "1ms"
  master:
    user: "root"
    password: "starunion"
    host: "127.0.0.1"
    port: "3306"
    database: "go-admin"
  slave:
    - user: "root"
      password: "starunion"
      host: "127.0.0.1"
      port: "3306"
      database: "go-admin"

redis:
  redisType: "alone"
  network: "127.0.0.1:6379"
  startAddr: ["127.0.0.1:6379"]
  active: 100
  idle: 100
  auth: ""
  connTimeout: "100ms"
  readTimeout: "100ms"
  writeTimeout: "100ms"
  idleTimeout: "100ms"

jwt:
  key: go-admin
  expire: 360
