logger:
  #Level 0 紧急的 1警报 2重要的 3错误 4警告 5提示 6信息 7调试
  consoleShow: true
  consoleLevel:  7
  fileWrite:  true
  fileLevel:  7
  multiFileWrite: false
  multiFileLevel: 7

httpServer:
  port: 8123

rpcServer:
  model: 1
  etcd: ["12345"]
  basePath: "go-admin"
