definitions:
  auth.LoginParams:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
  auth.LoginResp:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  description: |
    基于RpcX + Vue + Element UI的前后端分离权限管理系统的接口文档
  title: go-admin API
  version: 1.0.0
paths:
  /api/login:
    post:
      description: 用户登录
      parameters:
      - description: 登录参数
        in: body
        name: deptName
        required: true
        schema:
          $ref: '#/definitions/auth.LoginParams'
      responses:
        "200":
          description: '{"code": 200, "data": [...]}'
          schema:
            $ref: '#/definitions/auth.LoginResp'
      summary: 登录
      tags:
      - 用户登录登出
  /api/logout:
    post:
      description: 用户登录
      responses:
        "200":
          description: '{"code": 200, "data": [...]}'
          schema:
            type: string
      summary: 登出
      tags:
      - 用户登录登出
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
